#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: jahid_jmdn.yaml
    original_table_name: jahid_jmdn
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: jahid_jmdn
schema: core
description: JAHID提供のサブマスタ内JMDNマスタ

#- columns info -------------------------------------------
columns:
- name: jahid_jmdn_id
  old_name: id
  description: ID
  data_type: serial
  primary_key: true
  nullable: true
  comment: Serial値
- name: jmdn_management_code
  old_name: jmdnid
  description: JMDN管理コード
  data_type: text
  primary_key: false
  nullable: true
  comment: 数値のみだが先頭にゼロ付きがあるのでtextとする
- name: jmdn_code
  old_name: jmdncode
  description: JMDNコード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: jmdn_name
  old_name: jmdnname
  description: 一般的名称
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_code
  old_name: ruibetsucode
  description: 類別コード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_name
  old_name: ruibetsuname
  description: 類別名称
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: special_maintenance_category
  old_name: tokuteihosyukanrikbn
  description: 特定保守管理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: class_classification
  old_name: classbunruikbn
  description: クラス分類区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jahid_created_at
  old_name: jahidregdate
  description: 登録日時
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: jahid_created_by
  old_name: jahidreguserid
  description: 登録者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jahid_updated_at
  old_name: jahidlastupdate
  description: 更新日時
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: jahid_updated_by
  old_name: jahidupdateuserid
  description: 更新者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jahid_program_id
  old_name: jahidproguramid
  description: 更新プログラムID
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: repair_category
  old_name: syurikbn
  description: 修理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: installation_management_category
  old_name: settikanrikbn
  description: 設置管理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
