#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: jahid_products.yaml
    original_table_name: jahid_products
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: jahid_products
schema: core
description: JAHID提供の商品マスタ

#- columns info -------------------------------------------
columns:
- name: jahid_product_id
  old_name: id
  description: ID
  data_type: serial
  primary_key: true
  nullable: true
  comment: Serial値
- name: record_management_number
  old_name: recnumber
  description: レコード管理番号
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: item_management_number
  old_name: itemnumber
  description: アイテム管理番号
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: valid_from
  old_name: startdate_use
  description: 摘要開始日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: valid_to
  old_name: enddate_use
  description: 摘要終了日
  data_type: date
  primary_key: false
  nullable: true
  comment: 現在利用中の最新レコードはNULLがセット
- name: jan_code
  old_name: jancode
  description: JANコード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_name
  old_name: productname
  description: 商品名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_name_short
  old_name: ryaku
  description: 商品名略称
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_name_kana
  old_name: kanamei
  description: 商品名カナ
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_specification
  old_name: kikaku
  description: 規格
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_specification_halfwidth
  old_name: kikaku_hankaku
  description: 規格（半角）
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_number
  old_name: productnumber
  description: 製品番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: catalogue_code
  old_name: cataloguecode
  description: カタログコード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: search_product_number
  old_name: searchproductnumber
  description: 検索用製品番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: maker_code
  old_name: makercode
  description: 製造販売業者コード
  data_type: integer
  primary_key: false
  nullable: true
  comment: 業者マスタ.業者コード
- name: maker_name
  old_name: makername
  description: 製造販売業者名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: vendor_code
  old_name: vendorcode
  description: 国内総販売元業者コード
  data_type: integer
  primary_key: false
  nullable: true
  comment: 業者マスタ.業者コード
- name: vendor_name
  old_name: vendorname
  description: 国内総販売元業者名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: retail_price
  old_name: price
  description: 希望小売価格
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: price_category
  old_name: pricekbn
  description: 価格区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: retail_price_start_date
  old_name: startdate_price
  description: 希望小売価格適用日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: retail_price_package_indicator
  old_name: packagetype_price
  description: 希望小売価格梱包インジケータ
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: retail_price_previous
  old_name: price_old
  description: 旧希望小売価格
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: tax_category
  old_name: taxkbn
  description: 税率区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞税率区分
- name: hospital_min_package_indicator
  old_name: packagetype_hpmin
  description: 医療機関最小購入単位梱包インジケータ
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: vendor_min_package_indicator
  old_name: packagetype_vendormin
  description: 製造業者最小出荷単位梱包インジケータ
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: vendor_min_shipment_quantity
  old_name: shipqty_vendormin
  description: 製造業者最小出荷単位数量
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jmdn_code
  old_name: jmdncode
  description: JMDNコード
  data_type: text
  primary_key: false
  nullable: true
  comment: JMDNマスタ.JMDNコード
- name: common_name
  old_name: commonname
  description: 一般的名称
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: approval_number
  old_name: approvalnumber
  description: 承認番号／届出番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: class_type
  old_name: classtype
  description: クラス分類
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞クラス分類区分
- name: maintenance_category
  old_name: maintainkbn
  description: 特定保守管理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞特定保守管理区分
- name: repair_category
  old_name: reparekbn
  description: 修理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞修理区分
- name: installation_category
  old_name: setupkbn
  description: 設置管理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞設置管理区分
- name: poison_category
  old_name: dokugekikbn
  description: 毒劇区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞毒劇区分
- name: storage_category
  old_name: keepkbn
  description: 保管区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞保管区分
- name: reimbursement_request_category
  old_name: shoukanseiqkbn
  description: 材料償還請求区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞材料償還請求区分
- name: biological_origin_category
  old_name: seibutsuyuraikbn
  description: 生物由来製品区分
  data_type: integer
  primary_key: false
  nullable: true
  comment: 区分マスタ＞生物由来製品区分
- name: package_insert_info_code
  old_name: docinfocode
  description: 添付文書情報管理コード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: medical_affairs_code
  old_name: ijicode
  description: 医事コード
  data_type: text
  primary_key: false
  nullable: true
  comment: 医事コードマスタ.医事コード
- name: medical_material_name
  old_name: iryouzairyouname
  description: （現）特定保険医療材料名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_note
  old_name: biko
  description: 償還請求備考
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_total_price
  old_name: price_shoukan
  description: 償還価格合計
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_classification_code
  old_name: shoukanbunruicode
  description: （現）償還分類コード
  data_type: integer
  primary_key: false
  nullable: true
  comment: 償還分類マスタ.償還分類コード
- name: reimbursement_classification_start_date
  old_name: startdate_shoukanbunrui
  description: （現）償還分類適用開始日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_classification_price
  old_name: price_shoukanbunrui
  description: （現）償還分類価格
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_classification_code_old
  old_name: shoukanbunruicode_old
  description: （旧）償還分類コード
  data_type: integer
  primary_key: false
  nullable: true
  comment: 償還分類マスタ.償還分類コード
- name: reimbursement_classification_start_date_old
  old_name: startdate_shoukanbunrui_old
  description: （旧）償還分類適用開始日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_classification_price_old
  old_name: price_shoukanbunrui_old
  description: （旧）償還分類価格
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: classification_code
  old_name: bunruicode
  description: 分類コード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: medis_classification_code
  old_name: medisbunruicode
  description: MEDIS分類コード
  data_type: integer
  primary_key: false
  nullable: true
  comment: MEDIS分類マスタ.分類コード
- name: medis_vendor_short_name
  old_name: medisvendorname
  description: MEDIS登録企業略名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: medis_registered_at
  old_name: startdate_medis
  description: MEDIS初期登録日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: medis_updated_at
  old_name: lastupdate_medis
  description: MEDIS最終登録日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: shipment_start_date
  old_name: startdate_ship
  description: 出荷開始日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: production_end_date
  old_name: stopdate
  description: 製造停止期日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: item_number_old
  old_name: itemnumber_old
  description: 旧アイテム管理番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: jan_code_old
  old_name: jancode_old
  description: 旧JANコード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_image_url
  old_name: linkurl
  description: 商品画像ページリンク先
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: jahid_created_at
  old_name: jahidregdate
  description: 登録日
  data_type: date
  primary_key: false
  nullable: true
  comment: 提供されたJAHIDに記載せれている登録日で実際に作業した日付とは異なる
- name: jahid_updated_at
  old_name: jahidlastupdate
  description: 更新日
  data_type: date
  primary_key: false
  nullable: true
  comment: 提供されたJAHIDに記載せれている更新日で実際に作業した日付とは異なる
- name: reimbursement_unit_quantity_pi0
  old_name: qty_pi0
  description: PI-0の保険償還単位数
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: reimbursement_price_pi0
  old_name: price_shoukan_pi0
  description: PI-0の償還価格
  data_type: bigint
  primary_key: false
  nullable: true
  comment: null
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
