#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: jahid_medical_codes.yaml
    original_table_name: jahid_medical_codes
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: jahid_medical_codes
schema: core
description: JAHID提供のサブマスタ内の医事コードマスタ

#- columns info -------------------------------------------
columns:
- name: jahid_medical_codes_id
  old_name: id
  description: ID
  data_type: serial
  primary_key: true
  nullable: true
  comment: Serial値
- name: medical_code
  old_name: ijicode
  description: 医事コード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: medical_name
  old_name: ijiname
  description: 医事名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: jahid_created_at
  old_name: jahidregdate
  description: 登録日時
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: jahid_reguser_id
  old_name: jahidreguserid
  description: 登録者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jahid_updated_at
  old_name: jahidlastupdate
  description: 更新日時
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: jahid_updateuser_id
  old_name: jahidupdateuserid
  description: 更新者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jahid_proguram_id
  old_name: jahidproguramid
  description: 更新プログラムID
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
