#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: medical_device_repair_history.yaml
    original_table_name: medical_device_repair_history
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: medical_device_repair_history
schema: core
description: 修理履歴テーブル

#- columns info -------------------------------------------
columns:
- name: medical_facility_id
  old_name: hpcode
  description: 病院コード
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_seq_id
  old_name: hpseq
  description: 病院内連番
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_name
  old_name: hpname
  description: 病院名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: received_at
  old_name: recvdate
  description: データ受領日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: device_number
  old_name: menumber
  description: 機器番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: repair_id
  old_name: repairid
  description: 管理番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: trouble_date
  old_name: troubledate
  description: 発生日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: completion_date
  old_name: completedate
  description: 修理完了日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: requesting_department
  old_name: grprequest
  description: 依頼部門
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_name
  old_name: productname
  description: 製品名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: model_number
  old_name: modelnumber
  description: 型番
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: serial_number
  old_name: serialnumber
  description: シリアル番号
  data_type: text
  primary_key: false
  nullable: true
  comment: NULLの場合は[未登録]をセット
- name: category_major
  old_name: bunrui_1
  description: 大分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_middle
  old_name: bunrui_2
  description: 中分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_minor
  old_name: bunrui_3
  description: 小分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: manufacturer_name
  old_name: makername
  description: メーカー
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: user_department
  old_name: grpuser
  description: 発生部門
  data_type: text
  primary_key: false
  nullable: true
  comment: 利用部門
- name: repair_category
  old_name: kbnrepair
  description: 保守区分
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: event_note
  old_name: eventnote
  description: 発生状況
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: failure_reason
  old_name: reasonnote
  description: 故障理由
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: work_note
  old_name: worknote
  description: 作業内容
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: repair_result
  old_name: resultnote
  description: 修理結果
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: downtime_hours
  old_name: downtime
  description: 障害時間
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: device_category
  old_name: bunrui
  description: 機器分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: calculated_trouble_date
  old_name: troubledatecalc
  description: 発生日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: calculated_completion_date
  old_name: completedatecalc
  description: 修理完了日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: calculated_downtime_hours
  old_name: downtimecalc
  description: 障害時間
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
