#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: medical_device_rental_history.yaml
    original_table_name: medical_device_rental_history
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: medical_device_rental_history
schema: core
description: 貸出履歴テーブル

#- columns info -------------------------------------------
columns:
- name: medical_facility_id
  old_name: hpcode
  description: 病院コード
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_seq_id
  old_name: hpseq
  description: 病院内連番
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_name
  old_name: hpname
  description: 病院名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: received_at
  old_name: recvdate
  description: データ受領日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: device_number
  old_name: menumber
  description: 機器番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: rental_id
  old_name: rentalid
  description: 管理番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_name
  old_name: productname
  description: 製品名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: model_number
  old_name: modelnumber
  description: 型番
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: serial_number
  old_name: serialnumber
  description: シリアル番号
  data_type: text
  primary_key: false
  nullable: true
  comment: NULLの場合は[未登録]をセット
- name: manufacturer_name
  old_name: makername
  description: メーカー
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_major
  old_name: bunrui_1
  description: 大分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_middle
  old_name: bunrui_2
  description: 中分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_minor
  old_name: bunrui_3
  description: 小分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: rental_start_date
  old_name: startdate
  description: 貸出日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: recipient_department
  old_name: recipientgrp
  description: 貸出先
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: return_date
  old_name: returndate
  description: 返却日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: return_department
  old_name: returngrp
  description: 返却先
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: created_by
  data_type: TEXT
  nullable: false
  description: 作成者ID（ユーザーID・システムID）
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_by
  data_type: TEXT
  nullable: false
  description: 最終更新者ID（ユーザーID・システムID）
- name: device_category
  old_name: bunrui
  description: 機器分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: calculated_rental_start_date
  old_name: startdatecalc
  description: 貸出日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: 時間情報が無ければ00:00:00
- name: calculated_return_date
  old_name: returndatecalc
  description: 返却日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: 時間情報が無ければ23:59:59
