#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: mhlw_medical_facility.yaml
    original_table_name: mhlw_medical_facility
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: mhlw_medical_facility
schema: core
description: 厚労省が公開している病院情報

#- columns info -------------------------------------------
columns:
- name: nhlw_medical_facility_id
  old_name: id
  description: ID
  data_type: serial
  primary_key: true
  nullable: true
  comment: null
- name: primary_medical_facility_type
  old_name: regtype_pri
  description: 医科種別_主
  data_type: integer
  primary_key: false
  nullable: true
  comment: '登録時の医科種別

    1 : 医科

    2 : 歯科

    3 : 薬局


    医科併設は歯科がメインで医科が副、歯科併設は医科がメインで、歯科が副、上記医科種別の場合、secはNone'
- name: secondary_medical_facility_type
  old_name: regtype_sec
  description: 医科種別_副
  data_type: integer
  primary_key: false
  nullable: true
  comment: '登録時の医科種別

    1 : 医科

    2 : 歯科

    3 : 薬局


    医科併設は歯科がメインで医科が副、歯科併設は医科がメインで、歯科が副、上記医科種別の場合、secはNone'
- name: prefecture_code
  old_name: prefcode
  description: 都道府県コード
  data_type: text
  primary_key: false
  nullable: true
  comment: (2024.10.22)医療機関コードが全国で重複するレコードが存在した為、都道府県コードとセットのユニークキーとする。システム的にはidがキーなので、ロジックのみで対応可能だが、項目の配置を上位に移動。
- name: primary_nhlw_medical_facility_code
  old_name: hpcodepri
  description: 医療機関コード＿主
  data_type: text
  primary_key: false
  nullable: true
  comment: '医科種別が併設の場合、メインが主で併設分が副に登録される。

    3つの数字で構成されるがデリミターは地域によって異なる為、データ登録時は0000000で固定する。ただし桁が増えることも考慮して余裕を持たせる。'
- name: secondary_nhlw_medical_facility_code
  old_name: hpcodesec
  description: 医療機関コード＿副
  data_type: text
  primary_key: false
  nullable: true
  comment: '医科種別が併設の場合、メインが主で併設分が副に登録される。

    3つの数字で構成されるがデリミターは地域によって異なる為、データ登録時は0000000で固定する。ただし桁が増えることも考慮して余裕を持たせる。'
- name: nhlw_medical_facility_code_local
  old_name: hpcodelocal
  description: 医療機関コード_支局独自
  data_type: text
  primary_key: false
  nullable: true
  comment: 厚労省各支局独自のコード
- name: nhlw_open_medical_facility_code_medical
  old_name: openhpcodemed
  description: オープンデータ医療機関コード_医科
  data_type: text
  primary_key: false
  nullable: true
  comment: 病床数情報がある病院に限り紐付ける番号が存在。このコードが登録されている場合は、病棟マスタ・入院情報マスタの連携がされている
- name: nhlw_open_medical_facility_code_dental
  old_name: openhpcodedental
  description: オープンデータ医療機関コード_歯科
  data_type: text
  primary_key: false
  nullable: true
  comment: 病床数情報がある病院に限り紐付ける番号が存在。このコードが登録されている場合は、病棟マスタ・入院情報マスタの連携がされている
- name: is_active
  old_name: isactive
  description: 稼働状態
  data_type: integer
  primary_key: false
  nullable: true
  comment: '0：休止

    1：現存

    9：回答なし（辞退）'
- name: medical_facility_name
  old_name: hpname
  description: 医療機関名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: secondary_medical_area_code
  old_name: medareacode
  description: 二次医療圏コード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: municipality_code
  old_name: towncode
  description: 市区町村コード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: postal_code
  old_name: postcode
  description: 郵便番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: address
  old_name: address
  description: 所在地
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: phone_number
  old_name: tel
  description: 電話番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: count_fulltime_total
  old_name: countmaintotal
  description: 勤務医数（常勤・合計）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_fulltime_doctor
  old_name: countmaindoc
  description: 勤務医数（常勤・医師）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_fulltime_dentist
  old_name: countmaindental
  description: 勤務医数（常勤・歯科医師）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_fulltime_pharmacist
  old_name: countmaindrug
  description: 勤務医数（常勤・薬剤師）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_fulltime_other
  old_name: countmainother
  description: 勤務医数（常勤・その他）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_parttime_total
  old_name: countsubtotal
  description: 勤務医数（非常勤・合計）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_parttime_doctor
  old_name: countsubdoc
  description: 勤務医数（非常勤・医師）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_parttime_dentist
  old_name: countsubdental
  description: 勤務医数（非常勤・歯科医師）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_parttime_pharmacist
  old_name: countsubdrug
  description: 勤務医数（非常勤・薬剤師）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_parttime_other
  old_name: countsubother
  description: 勤務医数（非常勤・その他）
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: count_beds
  old_name: countbeds
  description: 病床数
  data_type: jsonb
  primary_key: false
  nullable: true
  comment: null
- name: departments
  old_name: departments
  description: 診療科目
  data_type: jsonb
  primary_key: false
  nullable: true
  comment: null
- name: hospital_founder
  old_name: hpregusername
  description: 開設者氏名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: hospital_administrator
  old_name: hpmanageusername
  description: 管理者氏名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: hospital_opening_date
  old_name: hpstartdate
  description: 開業日（指定年月日）
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: registration_reason
  old_name: regreason
  description: 登録理由
  data_type: integer
  primary_key: false
  nullable: true
  comment: '1: ''新規開設'',

    2: ''継承開設'',

    3: ''開設変更'',

    4: ''移転開設'',

    5: ''法人化開設'',

    6: ''開設者変更'',

    7: ''所在地変更'',

    8: ''組織変更'',

    99: ''その他'''
- name: hospital_registration_date
  old_name: hpregdate
  description: 指定期開始日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: medical_facility_type
  old_name: hptype
  description: 医療機関種別
  data_type: jsonb
  primary_key: false
  nullable: true
  comment: 'hptype

    総合病院、病院、診療所、地域支援、療養病床、特定機能、薬局

    ※厚労省の病院情報に変動があれば勝手に増えていく'
- name: nhlw_file_updated_at
  old_name: fileupdatedate
  description: 厚労省ファイル更新日
  data_type: date
  primary_key: false
  nullable: true
  comment: 厚労省のサイトに記載されたファイル更新日
- name: nhlw_site_upload_date
  old_name: siteuploaddate
  description: 厚労省サイト更新日
  data_type: date
  primary_key: false
  nullable: true
  comment: 厚労省のサイトに記載されたサイト更新日
- name: registration_file_1
  old_name: regfilename1
  description: 登録ファイル①
  data_type: text
  primary_key: false
  nullable: true
  comment: '登録時のファイル名、修正が入る場合はそのファイル名で更新

    ※内容チェックを行い更新対象が存在しない場合、この項目は更新しない

    ※主・副と並びが同じにならないこともあり、それで問題無い為、主副の名前は使っていない'
- name: registration_seq_no_1
  old_name: regnumber1
  description: 登録時項番①
  data_type: integer
  primary_key: false
  nullable: true
  comment: '登録時の項番、修正が入る場合はそのファイルの項番で更新

    ※内容チェックを行い更新対象が存在しない場合、この項目は更新しない'
- name: registration_file_2
  old_name: regfilename2
  description: 登録ファイル②
  data_type: text
  primary_key: false
  nullable: true
  comment: ①と同一だが、2つのファイルに同一の情報が入っている併設時は、ここに別ファイル・別項番をセット。
- name: registration_seq_no_2
  old_name: regnumber2
  description: 登録時項番②
  data_type: integer
  primary_key: false
  nullable: true
  comment: ①と同一だが、2つのファイルに同一の情報が入っている併設時は、ここに別ファイル・別項番をセット。
- name: checked_at
  old_name: checkdate
  description: 内容確認日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: '変更の有無確認を行った日時

    ※厚労省提供情報に掲載されなくなるとこの日付の更新が行われなくなる（いつまで掲載されていたかが明確）'
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: レコードの追加を行った日時
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: レコードの変更を行った日時（ただし内容確認日の更新のみであれば、この項目は更新しない）
