#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: msthospital.yaml
    original_table_name: msthospital
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: mst_medical_facility
description: 管理する医療機関を管理するマスタ

#- columns info -------------------------------------------
columns:
- name: medical_facility_id
  old_name: hpcode
  description: 病院コード
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_name
  old_name: hpname
  description: 病院名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: mhlw__medical_facility_code
  old_name: govhpcode
  description: 医療機関番号
  data_type: text
  primary_key: false
  nullable: true
  comment: 3つの数字で構成されるがデリミターは地域によって異なる為、データ登録時は00-0000-0で固定する。ただし桁が増えることも考慮して余裕を持たせる。
- name: mhlw_open_medical_facility_code
  old_name: openhpcode
  description: オープンデータ医療機関コード
  data_type: text
  primary_key: false
  nullable: true
  comment: 病床数情報がある病院に限り紐付ける番号が存在。このコードが登録されている場合は、病棟マスタ・入院情報マスタの連携がされている
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
