#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成
  conversion_info:
    source_file: source_medical_device.yaml
    original_table_name: source_medical_device
    conversion_date: '2025-09-18'
    applied_rules: rename_dictionary.yaml v1

#- tableinfo ----------------------------------------------
table_name: source_medical_device
schema: raw
description: 取込_病院機器台帳テーブル

#- columns info -------------------------------------------
columns:
- name: medical_facility_id
  old_name: hpcode
  description: 病院コード
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_seq_id
  old_name: hpseq
  description: 病院内連番
  data_type: integer
  primary_key: true
  nullable: true
  comment: null
- name: medical_facility_name
  old_name: hpname
  description: 病院名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: received_at
  old_name: recvdate
  description: データ受領日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: device_number
  old_name: menumber
  description: 機器番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: managing_department
  old_name: grpmanage
  description: 管理部門
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: user_department
  old_name: grpuser
  description: 利用部門
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: purchasing_department
  old_name: grppurchase
  description: 購入部門
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: serial_number
  old_name: serialnumber
  description: シリアル番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: purchase_date
  old_name: datepurchase
  description: 購入日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: delivery_date
  old_name: datestock
  description: 納入日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: operation_start_date
  old_name: dateoperationstart
  description: 初回稼働日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: purchase_category
  old_name: kbnpurchase
  description: 購入区分
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: asset_number
  old_name: assetnumber
  description: 資産番号
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: disposal_date
  old_name: datedisposal
  description: 廃棄日
  data_type: date
  primary_key: false
  nullable: true
  comment: null
- name: location_fixed
  old_name: mestatus
  description: 場所固定
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: product_name
  old_name: productname
  description: 製品名
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: model_number
  old_name: modelnumber
  description: 型番
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: manufacturer_name
  old_name: makername
  description: メーカー
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_major
  old_name: bunrui_1
  description: 大分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_middle
  old_name: bunrui_2
  description: 中分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: category_minor
  old_name: bunrui_3
  description: 小分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: legal_service_life_years
  old_name: durableyears_legal
  description: 法廷耐用年数
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: facility_service_life_years
  old_name: durableyears_hp
  description: 院内耐用年数
  data_type: integer
  primary_key: false
  nullable: true
  comment: null
- name: jan_code
  old_name: jancode
  description: JANコード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: jmdn_code
  old_name: jmdncode
  description: JMDNコード
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: class_type
  old_name: classtype
  description: クラス分類
  data_type: text
  primary_key: false
  nullable: true
  comment: null
- name: created_at
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
- name: updated_at
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment: null
