#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: H.Miyazawa
  history:
  - version: 1.0.0
    date: '2025-06-27'
    author: H.Miyazawa
    comment: OptiServe用のデータベース設計
  - version: 1.1.0
    date: '2025-08-13'
    author: H.Miyazawa
    comment: '登録、更新のユーザーIDを追加'
  - version: 1.2.0
    date: '2025-08-22'
    author: H.Miyazawa
    comment: 'ユーザーIDをintegerからtextに変更。'

#- tableinfo ----------------------------------------------
table_name: report_publication_log
description: 医療機関向けレポートの公開履歴テーブル
#- columns info -------------------------------------------
columns:
  - name: publication_id
    description: レポート公開ID
    data_type: serial
    primary_key: true
    nullable: false
    comment: null

  - name: medical_id
    description: 医療機関ID
    data_type: integer
    primary_key: false
    nullable: false
    comment: null
    references:
      table: mst_medical_facility
      column: medical_id
      enforced: false  # DB制約無し
      on_delete: restrict  # restrict, cascade, set null, no action
      on_update: restrict
      comment: 'mst_medical_facilityテーブルのmedical_idを参照。'

  - name: publication_ym
    description: レポート公開年月
    data_type: text
    primary_key: false
    nullable: false
    comment: 'レポートが公開された年月。'

  - name: file_type
    description: 公開したファイルの種類
    data_type: integer
    primary_key: false
    nullable: false
    comment: '公開したファイルの種類。1: 分析レポート, 2: 故障リスト, 3: 未実績リスト。'

  - name: file_name
    description: 公開したファイル名
    data_type: text
    primary_key: false
    nullable: false
    comment: '公開したファイルの名前。'

  - name: upload_datetime
    description: サイトへの更新日時
    data_type: timestamp
    primary_key: false
    nullable: false
    comment: 'サイトへの更新を行った日時'

  - name: download_user_id
    description: ダウンロードを行ったユーザーID
    data_type: text
    primary_key: false
    nullable: false
    comment: 'ダウンロードを行ったユーザーのID。ユーザーマスタのuser_idと紐づく。最初にダウンロードしたユーザーのみ登録される。'
    references:
      table: m_mst_user
      column: user_id
      enforced: false  # DB制約無し
      on_delete: restrict  # restrict, cascade, set null, no action
      on_update: restrict
      comment: 'm_mst_userテーブルのuser_idを参照。ダウンロードを行ったユーザーのID。'

  - name: download_datetime
    description: ユーザーのダウンロード日時
    data_type: timestamp
    primary_key: false
    nullable: true
    comment: 'ユーザーがファイルのダウンロードを行った日時。ダウンロードが行われていない場合はNULL。最初にダウンロードした日時のみ登録される。'

  - name: reg_user_id
    description: 登録ユーザーID
    data_type: text
    primary_key: false
    nullable: false
    comment: 'このレコードの登録を行ったユーザーのID。'
    references:
      table: m_mst_user
      column: user_id
      enforced: false  # DB制約無し
      on_delete: restrict  # restrict, cascade, set null, no action
      on_update: restrict

  - name: regdate
    description: データ作成日
    data_type: timestamp
    primary_key: false
    nullable: false
    comment: null

  - name: update_user_id
    description: 更新ユーザーID
    data_type: text
    primary_key: false
    nullable: false
    comment: 'このレコードの更新を行ったユーザーのID。'
    references:
      table: m_mst_user
      column: user_id
      enforced: false  # DB制約無し
      on_delete: restrict  # restrict, cascade, set null, no action
      on_update: restrict

  - name: lastupdate
    description: 最終更新日
    data_type: timestamp
    primary_key: false
    nullable: false
    comment: null

#- indexes info -------------------------------------------
indexes:
- name: idx_report_publication_log_medical_id
  columns: [medical_id]
  unique: false
  note: '医療機関IDのインデックス。医療機関ごとのレポート公開履歴を効率的に検索するためのインデックス。'

- name: idx_publication_ym
  columns: [publication_ym]
  unique: false
  note: 'レポート公開年月のインデックス。特定の年月に公開されたレポートを効率的に検索するためのインデックス。'
