#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成

#- tableinfo ----------------------------------------------
table_name: mstjahidshoukanbunrui
description: JAHID提供のサブマスタ内の償還分類マスタ

#- columns info -------------------------------------------
columns:
- name: id
  old_name: id
  description: ID
  data_type: serial
  primary_key: true
  nullable: true
  comment: Serial値
- name: kanricode
  old_name: kanricode
  description: 償還管理コード
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: startdate
  old_name: startdate
  description: 適用開始日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: enddate
  old_name: enddate
  description: 適用終了日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: bunruinumber
  old_name: bunruinumber
  description: 償還分類番号
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruicode1
  old_name: bunruicode1
  description: 償還分類コード1
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruicode2
  old_name: bunruicode2
  description: 償還分類コード2
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruicode3
  old_name: bunruicode3
  description: 償還分類コード3
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruiname1
  old_name: bunruiname1
  description: 償還分類名1
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruiname2
  old_name: bunruiname2
  description: 償還分類名2
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruiname3
  old_name: bunruiname3
  description: 償還分類名3
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruiname
  old_name: bunruiname
  description: 償還分類名
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: ryakuname
  old_name: ryakuname
  description: 償還分類略名
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunruimark
  old_name: bunruimark
  description: 償還分類記号
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: price
  old_name: price
  description: 償還価格
  data_type: bigint
  primary_key: false
  nullable: true
  comment:
- name: unit
  old_name: unit
  description: 算定単位
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: memo
  old_name: memo
  description: 償還価格算定留意事項
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: biko
  old_name: biko
  description: 償還請求備考
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: ijicode
  old_name: ijicode
  description: 医事コード
  data_type: text
  primary_key: false
  nullable: true
  comment: 複数の医事コードが登録有り
- name: jahidregdate
  old_name: jahidregdate
  description: 登録日時
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: jahidreguserid
  old_name: jahidreguserid
  description: 登録者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: jahidlastupdate
  old_name: jahidlastupdate
  description: 更新日時
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: jahidupdateuserid
  old_name: jahidupdateuserid
  description: 更新者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: jahidproguramid
  old_name: jahidproguramid
  description: 更新プログラムID
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: regdate
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment:
- name: lastupdate
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment:
