#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成

#- tableinfo ----------------------------------------------
table_name: mstjahidjmdn
description: JAHID提供のサブマスタ内JMDNマスタ

#- columns info -------------------------------------------
columns:
- name: id
  old_name: id
  description: ID
  data_type: serial
  primary_key: true
  nullable: true
  comment: Serial値
- name: jmdnid
  old_name: jmdnid
  description: JMDN管理コード
  data_type: text
  primary_key: false
  nullable: true
  comment: 数値のみだが先頭にゼロ付きがあるのでtextとする
- name: jmdncode
  old_name: jmdncode
  description: JMDNコード
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: jmdnname
  old_name: jmdnname
  description: 一般的名称
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: ruibetsucode
  old_name: ruibetsucode
  description: 類別コード
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: ruibetsuname
  old_name: ruibetsuname
  description: 類別名称
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: tokuteihosyukanrikbn
  old_name: tokuteihosyukanrikbn
  description: 特定保守管理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: classbunruikbn
  old_name: classbunruikbn
  description: クラス分類区分
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: jahidregdate
  old_name: jahidregdate
  description: 登録日時
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: jahidreguserid
  old_name: jahidreguserid
  description: 登録者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: jahidlastupdate
  old_name: jahidlastupdate
  description: 更新日時
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: jahidupdateuserid
  old_name: jahidupdateuserid
  description: 更新者ID
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: jahidproguramid
  old_name: jahidproguramid
  description: 更新プログラムID
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: syurikbn
  old_name: syurikbn
  description: 修理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: settikanrikbn
  old_name: settikanrikbn
  description: 設置管理区分
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: regdate
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment:
- name: lastupdate
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment:
