#- metadata -----------------------------------------------
metadata:
  description: テーブル定義書
  author: Claude Code
  history:
  - version: 1.0.0
    date: '2025-09-12'
    author: Claude Code
    comment: Excel → YAML変換による初回作成

#- tableinfo ----------------------------------------------
table_name: tblrepairlog
description: 修理履歴テーブル

#- columns info -------------------------------------------
columns:
- name: hpcode
  old_name: hpcode
  description: 病院コード
  data_type: integer
  primary_key: true
  nullable: true
  comment:
- name: hpseq
  old_name: hpseq
  description: 病院内連番
  data_type: integer
  primary_key: true
  nullable: true
  comment:
- name: hpname
  old_name: hpname
  description: 病院名
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: recvdate
  old_name: recvdate
  description: データ受領日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: menumber
  old_name: menumber
  description: 機器番号
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: repairid
  old_name: repairid
  description: 管理番号
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: troubledate
  old_name: troubledate
  description: 発生日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: completedate
  old_name: completedate
  description: 修理完了日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: grprequest
  old_name: grprequest
  description: 依頼部門
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: productname
  old_name: productname
  description: 製品名
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: modelnumber
  old_name: modelnumber
  description: 型番
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: serialnumber
  old_name: serialnumber
  description: シリアル番号
  data_type: text
  primary_key: false
  nullable: true
  comment: NULLの場合は[未登録]をセット
- name: bunrui_1
  old_name: bunrui_1
  description: 大分類
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunrui_2
  old_name: bunrui_2
  description: 中分類
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: bunrui_3
  old_name: bunrui_3
  description: 小分類
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: makername
  old_name: makername
  description: メーカー
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: grpuser
  old_name: grpuser
  description: 発生部門
  data_type: text
  primary_key: false
  nullable: true
  comment: 利用部門
- name: kbnrepair
  old_name: kbnrepair
  description: 保守区分
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: eventnote
  old_name: eventnote
  description: 発生状況
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: reasonnote
  old_name: reasonnote
  description: 故障理由
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: worknote
  old_name: worknote
  description: 作業内容
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: resultnote
  old_name: resultnote
  description: 修理結果
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: downtime
  old_name: downtime
  description: 障害時間
  data_type: integer
  primary_key: false
  nullable: true
  comment:
- name: regdate
  old_name: regdate
  description: データ作成日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment:
- name: lastupdate
  old_name: lastupdate
  description: 最終更新日
  data_type: timestamp
  primary_key: false
  nullable: true
  comment:
- name: bunrui
  old_name: bunrui
  description: 機器分類
  data_type: text
  primary_key: false
  nullable: true
  comment:
- name: troubledatecalc
  old_name: troubledatecalc
  description: 発生日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: completedatecalc
  old_name: completedatecalc
  description: 修理完了日
  data_type: date
  primary_key: false
  nullable: true
  comment:
- name: downtimecalc
  old_name: downtimecalc
  description: 障害時間
  data_type: integer
  primary_key: false
  nullable: true
  comment:
